In [1]:
import tensorflow as tf

## tf.Session

In [2]:
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

b'Hello, TensorFlow!'


## tf.InteractiveSession

In [3]:
hello2 = tf.constant('Hello2, TensorFlow!!')
tf.InteractiveSession()
print(hello2.eval())

b'Hello2, TensorFlow!!'


## tf.one_hot

In [5]:
a = [1, 5, 0, 3, 0, 1]
b = tf.one_hot(a, 2)
print(sess.run(b))
print('====================')
print(b.eval())

[[ 0.  1.]
 [ 0.  0.]
 [ 1.  0.]
 [ 0.  0.]
 [ 1.  0.]
 [ 0.  1.]]
[[ 0.  1.]
 [ 0.  0.]
 [ 1.  0.]
 [ 0.  0.]
 [ 1.  0.]
 [ 0.  1.]]


## tf.reduce_sum

In [6]:
c = [[1, 2], [4, 5], [7, 8], [9, 10]]
d = [[0, 1], [1, 0], [1, 0], [1, 0]]

cd = tf.multiply(c, d) ## cg. tf.matmul
print(sess.run(cd))
print(sess.run(tf.reduce_sum(cd, 1)))
print(sess.run(tf.reduce_sum(cd, 0)))
print('============================')
print(tf.reduce_sum(cd, 0).eval())

[[0 2]
 [4 0]
 [7 0]
 [9 0]]
[2 4 7 9]
[20  2]
[20  2]


## tf.shape

In [25]:
print(sess.run(tf.shape(cd)))
print(cd)

[4 2]
Tensor("Mul_14:0", shape=(4, 2), dtype=int32)


In [3]:
import numpy as np

## np.random.choice

In [4]:
e = np.arange(5)
print(e)
k = np.random.choice(e, size=4, replace=False)
print(k)

[0 1 2 3 4]
[2 3 4 1]


In [43]:
p = 0.01 + (1.0 - 0.01) * np.exp(-0.0001 * 8000)
print(p)

0.454835674476


## np.argmax, np.max

In [63]:
m = np.array([[5, 2, 3, 6], [1, 1, 10, 9]])
print(m)
print(np.argmax(m))
print(np.max(m, axis=1))
print(np.max(m, axis=0))

[[ 5  2  3  6]
 [ 1  1 10  9]]
6
[ 6 10]
[ 5  2 10  9]


## maxtrix operation

In [87]:
next_states = np.array([[0, 0, 0], [1, 0, 0], [0, 0, 0]])
print((next_states == np.zeros(next_states.shape)))
episode_ends = (next_states == np.zeros(next_states.shape)).all(axis=1)
print(episode_ends)

target_Qs = np.array([[1, 2], [3, 4], [7, 8]])
print(target_Qs)
print(target_Qs[episode_ends])
target_Qs[episode_ends] = (0, 0)
print(target_Qs)

[[ True  True  True]
 [False  True  True]
 [ True  True  True]]
[ True False  True]
[[1 2]
 [3 4]
 [7 8]]
[[1 2]
 [7 8]]
[[0 0]
 [3 4]
 [0 0]]


## tf.reduce_mean

In [83]:
a = tf.constant([
    [
        [
            [1., 2., 3., 4.],
            [3., 4., 5., 6.],
            [5., 6., 7., 8.]
        ],
        [
            [7., 8., 9., 10.],
            [9., 10., 11., 12.],
            [11., 12., 13., 14.]
        ],
        [
            [14., 15., 16., 17.],
            [17., 18., 19., 20.],
            [21., 22., 23., 24.]
        ]
    ]
])

print('a shape = ', sess.run(tf.shape(a)))
print('==================================')
b = tf.reduce_mean(a, (1, 2))
print('b shape = ', sess.run(tf.shape(b)))
print('b value = ', sess.run(b))
print('==================================')
c = tf.layers.average_pooling2d(a, 3, 1)
print('c shape = ', sess.run(tf.shape(c)))
print('c value = ', sess.run(c))
print('==================================')
d = tf.reduce_mean(a)
print('d shape = ', sess.run(tf.shape(d)))
print('d value = ', sess.run(d))

a shape =  [1 3 3 4]
b shape =  [1 4]
b value =  [[  9.77777767  10.77777767  11.77777767  12.77777767]]
c shape =  [1 1 1 4]
c value =  [[[[  9.77777767  10.77777767  11.77777767  12.77777767]]]]
d shape =  []
d value =  11.2778


## tf.split

In [7]:
v = tf.constant([[3, 5, 11], [2, 4, 10], [1, 2, 9]])
print('v shape = ', sess.run(tf.shape(v)))
print('v value = \n', sess.run(v))

sp01, sp02 = tf.split(v, [2, 1], axis=1)
print('sp01 shape = ', sess.run(tf.shape(sp01)))
print('sp01 value = \n', sess.run(sp01))
print('sp01 squeeze value =\n', sess.run(tf.squeeze(sp01)))

print('sp02 shape = ', sess.run(tf.shape(sp02)))
print('sp02 value = \n', sess.run(sp02))

print('sp02 squeeze shape =', sess.run(tf.shape(tf.squeeze(sp02))))
print('sp02 squeeze value = \n', sess.run(tf.squeeze(sp02)))

v shape =  [3 3]
v value = 
 [[ 3  5 11]
 [ 2  4 10]
 [ 1  2  9]]
sp01 shape =  [3 2]
sp01 value = 
 [[3 5]
 [2 4]
 [1 2]]
sp01 squeeze value =
 [[3 5]
 [2 4]
 [1 2]]
sp02 shape =  [3 1]
sp02 value = 
 [[11]
 [10]
 [ 9]]
sp02 squeeze shape = [3]
sp02 squeeze value = 
 [11 10  9]


## tf.squeeze

In [50]:
s = tf.constant([
    [
        [3, 5, 11]
    ],
    [
        [2, 4, 10]
    ],
    [
        [1, 2, 9]
    ]
])

print('s shape = ', sess.run(tf.shape(s)))
print('s value = \n', sess.run(s))

ss = tf.squeeze(s)
print('ss shape = ', sess.run(tf.shape(ss)))
print('ss value = \n', sess.run(ss))

s shape =  [3 1 3]
s value = 
 [[[ 3  5 11]]

 [[ 2  4 10]]

 [[ 1  2  9]]]
ss shape =  [3 3]
ss value = 
 [[ 3  5 11]
 [ 2  4 10]
 [ 1  2  9]]


## tf.reduce_max

In [8]:
m = tf.constant([
        [11, 12],
        [10, 9],
        [ 9, 15]
])

print('m shape = ', sess.run(tf.shape(m)))
print('m value = \n', sess.run(m))

mr = tf.reduce_max(m, axis=1, keep_dims=True)
print('mr shape = ', sess.run(tf.shape(mr)))
print('mr value = \n', sess.run(mr))

mr2 = tf.reduce_max(m, axis=1, keep_dims=False)
print('mr2 shape = ', sess.run(tf.shape(mr2)))
print('mr2 value = \n', sess.run(mr2))

m shape =  [3 2]
m value = 
 [[11 12]
 [10  9]
 [ 9 15]]
mr shape =  [3 1]
mr value = 
 [[12]
 [10]
 [15]]
mr2 shape =  [3]
mr2 value = 
 [12 10 15]


## tf.reduce_sum

In [12]:
m = tf.constant([
        [11, 12],
        [10, 9],
        [ 9, 15]
])

print('m shape = ', sess.run(tf.shape(m)))
print('m value = \n', sess.run(m))

ms = tf.reduce_sum(m, axis=1, keep_dims=True)
print('ms shape = ', sess.run(tf.shape(ms)))
print('ms value = \n', sess.run(ms))

ms2 = tf.reduce_sum(m, axis=1, keep_dims=False)
print('ms2 shape = ', sess.run(tf.shape(ms2)))
print('ms2 value = \n', sess.run(ms2))

ms3 = tf.reduce_sum(m, axis=0, keep_dims=True)
print('ms3 shape = ', sess.run(tf.shape(ms3)))
print('ms3 value = \n', sess.run(ms3))

ms3_ = tf.reduce_sum(m, axis=0, keep_dims=False)
print('ms3_ shape = ', sess.run(tf.shape(ms3_)))
print('ms3_ value = \n', sess.run(ms3_))

ms4 = tf.reduce_sum(m, keep_dims=True)
print('ms4 shape = ', sess.run(tf.shape(ms4)))
print('ms4 value = \n', sess.run(ms4))

ms5 = tf.reduce_sum(m)
print('ms5 shape = ', sess.run(tf.shape(ms5)))
print('ms5 value = \n', sess.run(ms5))

m shape =  [3 2]
m value = 
 [[11 12]
 [10  9]
 [ 9 15]]
ms shape =  [3 1]
ms value = 
 [[23]
 [19]
 [24]]
ms2 shape =  [3]
ms2 value = 
 [23 19 24]
ms3 shape =  [1 2]
ms3 value = 
 [[30 36]]
ms3_ shape =  [2]
ms3_ value = 
 [30 36]
ms4 shape =  [1 1]
ms4 value = 
 [[66]]
ms5 shape =  []
ms5 value = 
 66


## tf.one_hot

In [69]:
hot = tf.constant([10, 9, 5])

print('hot shape = ', sess.run(tf.shape(hot)))
print('hot value = \n', sess.run(hot))

o_hot = tf.one_hot(hot, 11, dtype=tf.float32)
print('o_hot shape = ', sess.run(tf.shape(o_hot)))
print('o_hot value = \n', sess.run(o_hot))

hot shape =  [3]
hot value = 
 [10  9  5]
o_hot shape =  [ 3 11]
o_hot value = 
 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]


## tf.maximum

In [77]:
mu = tf.constant([10, 9, 0])

print('mu shape = ', sess.run(tf.shape(mu)))
print('mu value = \n', sess.run(mu))

mu = tf.maximum(1, mu)
print('mu shape = ', sess.run(tf.shape(mu)))
print('mu value = \n', sess.run(mu))

mum = tf.maximum(1, 20)
print('mum shape = ', sess.run(tf.shape(mum)))
print('mum value = \n', sess.run(mum))

mu shape =  [3]
mu value = 
 [10  9  0]
mu shape =  [3]
mu value = 
 [10  9  1]
mum shape =  []
mum value = 
 20


## tf.argmax

In [80]:
m = tf.constant([
        [11, 12, 15],
        [10, 9, 4],
        [ 9, 15, 14]
])
print('m shape = ', sess.run(tf.shape(m)))
print('m value = \n', sess.run(m))

argm = tf.argmax(m, 1)
print('argm shape = ', sess.run(tf.shape(argm)))
print('argm value = \n', sess.run(argm))

m shape =  [3 3]
m value = 
 [[11 12 15]
 [10  9  4]
 [ 9 15 14]]
argm shape =  [3]
argm value = 
 [2 0 1]


## tf.equal

In [82]:
a_ = tf.constant([1, 0, 1, 1])
b_ = tf.constant([1, 0, 0, 1])

eq = tf.equal(a_, b_)
print('eq shape = ', sess.run(tf.shape(eq)))
print('eq value = ', sess.run(eq))

feq = tf.to_float(eq)
print('feq shape = ', sess.run(tf.shape(feq)))
print('feq value = ', sess.run(feq))

eq shape =  [4]
eq value =  [ True  True False  True]
feq shape =  [4]
feq value =  [ 1.  1.  0.  1.]


## tf.abs

In [84]:
c_ = tf.constant([-1, 1, -20, -5])

cc_ = tf.abs(c_)
print('cc_ value = ', sess.run(cc_))

cc_ value =  [ 1  1 20  5]
